Repository Provable-Games/loot-survivor, pull requests merged in 2024-07, with the labels that each got.

#59 scales obstacle crit hit chance with adventurer level
  contracts/adventurer/src/adventurer.cairo
  contracts/adventurer/src/constants/adventurer_constants.cairo
Labels: game tuning

#60 scale beast ambush crit hit chance with adventurer level
  contracts/adventurer/src/adventurer.cairo
  contracts/adventurer/src/constants/adventurer_constants.cairo
  contracts/beasts/src/beast.cairo
  contracts/beasts/src/constants.cairo
  contracts/game/src/game/interfaces.cairo
  contracts/game/src/lib.cairo
Labels: game tuning

#61 modify adventurer leveling schema
  contracts/beasts/src/beast.cairo
  contracts/beasts/src/constants.cairo
  contracts/combat/src/combat.cairo
  contracts/combat/src/constants.cairo
  contracts/game/src/lib.cairo
  contracts/obstacles/src/obstacle.cairo
Labels: game tuning

#62 increases max beaset health from 511 to 1023
  contracts/beasts/src/constants.cairo
Labels: bug

#63 fixes stat overflow bug when dropping stat boosting item
  contracts/adventurer/src/adventurer.cairo
  contracts/game/src/lib.cairo
Labels: bug

#65 fixes beast distribution
  contracts/adventurer/src/adventurer.cairo
Labels: bug

#75 fixes beast attacking same armor location during equipment change
  contracts/game/src/lib.cairo
Labels: bug

#76 fixes integration tests
  .github/workflows/build.yml
  Scarb.lock
  Scarb.toml
  contracts/adventurer/src/adventurer_meta.cairo
  contracts/game/Scarb.toml
  contracts/game/src/game/interfaces.cairo
  contracts/game/src/lib.cairo
  contracts/game/src/tests/test_game.cairo
  contracts/lords/.gitignore
  contracts/lords/Scarb.toml
  contracts/lords/src/lib.cairo
  scripts/deploy.sh
  scripts/katana/katana_start.sh
Labels: enhancement

#77 improves starter beast experience
  contracts/adventurer/src/adventurer.cairo
  contracts/beasts/src/beast.cairo
  contracts/game/src/game/constants.cairo
  contracts/game/src/lib.cairo
  contracts/game/src/tests/test_game.cairo
Labels: bug, enhancement

#79 bump starknet version, OZ version, add in base 721 components
  Scarb.lock
  Scarb.toml
  contracts/game/Scarb.toml
  contracts/game/src/game/interfaces.cairo
  contracts/game/src/game/lib.cairo
  contracts/game/src/game/renderer.cairo
  contracts/game/src/lib.cairo
  contracts/game/src/tests/oz_constants.cairo
  contracts/game/src/tests/test_game.cairo
Labels: enhancement

#89 Delay item specials reveal
  contracts/adventurer/src/adventurer.cairo
  contracts/adventurer/src/adventurer_utils.cairo
  contracts/adventurer/src/bag.cairo
  contracts/adventurer/src/equipment.cairo
  contracts/game/src/game/RenderContract.cairo
  contracts/game/src/game/constants.cairo
  contracts/game/src/game/interfaces.cairo
  contracts/game/src/game/renderer.cairo
  contracts/game/src/lib.cairo
  contracts/loot/src/loot.cairo
Labels: enhancement

#92 handle pragma vrf payment
  contracts/adventurer/src/adventurer.cairo
  contracts/adventurer/src/adventurer_utils.cairo
  contracts/adventurer/src/bag.cairo
  contracts/adventurer/src/item.cairo
  contracts/game/src/game/constants.cairo
  contracts/game/src/game/interfaces.cairo
  contracts/game/src/lib.cairo
  contracts/game/src/tests/test_game.cairo
Labels: enhancement

#96 hardens battle entropy against prescience steering
  contracts/adventurer/src/adventurer.cairo
  contracts/adventurer/src/adventurer_utils.cairo
  contracts/adventurer/src/constants/adventurer_constants.cairo
  contracts/game/src/lib.cairo
Labels: enhancement

#97 adds game expiration and option to delay stat reveal
  contracts/adventurer/src/adventurer.cairo
  contracts/adventurer/src/adventurer_meta.cairo
  contracts/adventurer/src/adventurer_utils.cairo
  contracts/adventurer/src/stats.cairo
  contracts/game/src/game/RenderContract.cairo
  contracts/game/src/game/constants.cairo
  contracts/game/src/game/interfaces.cairo
  contracts/game/src/game/renderer.cairo
  contracts/game/src/lib.cairo
  contracts/game/src/tests/test_game.cairo
Labels: enhancement

#98 Add onchain adventurer obituaries
  contracts/game/src/game/constants.cairo
  contracts/game/src/game/interfaces.cairo
  contracts/game/src/lib.cairo
  contracts/game/src/tests/test_game.cairo
Labels: enhancement

#101 gas and contract size optimizations
  contracts/adventurer/Scarb.toml
  contracts/adventurer/src/adventurer.cairo
  contracts/adventurer/src/adventurer_meta.cairo
  contracts/adventurer/src/adventurer_utils.cairo
  contracts/adventurer/src/bag.cairo
  contracts/adventurer/src/constants/adventurer_constants.cairo
  contracts/adventurer/src/equipment.cairo
  contracts/adventurer/src/item.cairo
  contracts/adventurer/src/lib.cairo
  contracts/adventurer/src/stats.cairo
  contracts/beasts/src/constants.cairo
  contracts/beasts/src/lib.cairo
  contracts/game/src/game/encoding.cairo
  contracts/game/src/game/interfaces.cairo
  contracts/game/src/game/lib.cairo
  contracts/game/src/game/renderer.cairo
  contracts/game/src/lib.cairo
  contracts/game/src/tests/test_game.cairo
  contracts/loot/src/lib.cairo
  contracts/loot/src/loot.cairo
  contracts/market/src/market.cairo
  contracts/obstacles/src/obstacle.cairo
Labels: enhancement

#109 substantial refactor to reduce contract size and optimize gas
  contracts/adventurer/src/adventurer.cairo
  contracts/adventurer/src/adventurer_meta.cairo
  contracts/adventurer/src/constants/adventurer_constants.cairo
  contracts/adventurer/src/constants/discovery_constants.cairo
  contracts/adventurer/src/equipment.cairo
  contracts/adventurer/src/item.cairo
  contracts/adventurer/src/stats.cairo
  contracts/beasts/src/beast.cairo
  contracts/beasts/src/constants.cairo
  contracts/combat/src/combat.cairo
  contracts/combat/src/constants.cairo
  contracts/game/src/game/RenderContract.cairo
  contracts/game/src/game/constants.cairo
  contracts/game/src/game/interfaces.cairo
  contracts/game/src/game/renderer.cairo
  contracts/game/src/lib.cairo
  contracts/game/src/tests/test_game.cairo
  contracts/loot/src/constants.cairo
  contracts/loot/src/loot.cairo
  contracts/market/src/market.cairo
  contracts/obstacles/src/obstacle.cairo
  scripts/deploy.sh
Labels: enhancement

#110 store adventurers rank at time of death in AdventurerMetadata
  contracts/adventurer/src/adventurer_meta.cairo
  contracts/game/src/lib.cairo
  contracts/game/src/tests/test_game.cairo
Labels: enhancement

#113 limit vrf approval for all eth to mainnet and sepolia
  contracts/game/src/lib.cairo
Labels: bug
